### ISSUE TITLE
IGES morphing issue

### ISSUE THREAD

**Issue by guillaume-florent** [mathLab/PyGeM#137]
Morphing a closed hull has the hull and transom modified but the deck remains unchanged.
![image](https://user-images.githubusercontent.com/24844487/34698688-b4fdc638-f4d9-11e7-871c-57e31a3a2aa9.png)
Please see file at https://github.com/guillaume-florent/PyGeM/examples/example_hull_iges_FIXME.py and https://github.com/guillaume-florent/PyGeM/examples/example_hull_iges folder to repopduce the problem

**Comment by fazaghifari** [comment]
Hi,
Did you have fixed this issue? I have same the problem with my wind turbine blade geometry, The tip airfoil weren't deformed.
![tip](https://user-images.githubusercontent.com/26693799/39165386-65c75b9c-47ae-11e8-8293-836bd6e96a5f.PNG)
Please kindly tell me if you have fixed this issue.
Thanks.

**Comment by ndem0** [comment]
Hi, we are currently re-organizing all the file handlers modules in order to fix the known bug and clean the code. We hope this can fix the issue.

**Comment by andreamola** [comment]
![trimmed_flat_surface_cylinder_base](https://user-images.githubusercontent.com/8832692/93608822-5fd9ad80-f9cb-11ea-8ac1-715847d53611.png)

Hi everyone, I'm quite sorry for the delay, but now version 2.0 is coming out, and we noticed that one of the improvements in the new version likely solves the problem discussed in this thread.
From what I can speculate, the problem was occurring every time a trimmed surface defined on a plane was deformed remaining "in plane". I don't want to bore you with details about what is done differently now, but if you are curious, feel free to ask.
Anyway, the picture attached shows that when a cylinder is deformed only along the radial direction, the base circle is now deforming along with the lateral surface. Morally, this should be identical to the test cases posted in this thread.
So, if you are of course still interested in these problems, let me know if using the new version fixes them.
